language: node_js
node_js:
  - '8'

sudo: required
dist: trusty
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install sshpass -y

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm audit fix
  - npm run build
  - ls -la

after_success:
  - export SSHPASS=$DEPLOY_PASS
  - sshpass -e scp $DEPLOY_SOURCE $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
